name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ master ]  # 或者你默认分支的名字，如 master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.116.0'   # 你 hugo.toml 中声明的版本
          extended: false

      - name: Build Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
